services:
  lazyivqueue:
    container_name: lazyivqueue
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./LazyIVQueue/config:/app/LazyIVQueue/config
    ports:
      - "${LAZYIVQUEUE_PORT:-7070}:${LAZYIVQUEUE_PORT:-7070}"

networks:
  default:
    name: lazyivqueue_network
